mysql:
  gm:
    database: user
    host: sh-cdb-gx3qmzuz.sql.tencentcdb.com

  username: root
  password: rainbow_six
  port: 63132
  maxActive: 20
  minIdle: 1
  maxWait: 3000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  testWhileIdle: true

springfox:
  documentation:
    swagger:
      v2:
        path: "/internal/api-docs"
